/**
 * Unified Icons Component
 *
 * This file centralizes all icon exports from lucide-react and react-icons.
 * All apps should import icons from this file instead of directly from lucide-react or react-icons
 * to ensure consistency across the codebase.
 *
 * Usage:
 *   import { Icons } from "@dukkani/ui/components/icons";
 *   <Icons.arrowLeft className="..." />
 *   <Icons.google className="..." />
 */

import {
  AlertCircle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  BookIcon,
  CameraIcon,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  Circle,
  CirclePlay,
  Clock,
  CompassIcon,
  Copy,
  Eye,
  EyeOff,
  FileText,
  Gamepad2Icon,
  Globe,
  GripVertical,
  HouseIcon,
  Info,
  Key,
  LandmarkIcon,
  LaptopIcon,
  LayoutDashboard,
  LayoutGridIcon,
  Loader2,
  LockIcon,
  type LucideIcon,
  MapPin,
  Megaphone,
  MessageSquareX,
  Minus,
  Moon,
  MoreHorizontal,
  OctagonX,
  PackageCheck,
  PackageIcon,
  PanelLeft,
  PencilIcon,
  Phone,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Share2,
  ShieldCheck,
  ShirtIcon,
  ShoppingCart,
  ShoppingCartIcon,
  SlidersHorizontal,
  SparklesIcon,
  Star,
  StoreIcon,
  Sun,
  Trash2Icon,
  TriangleAlert,
  TrophyIcon,
  Truck,
  Upload,
  User2Icon,
  Users,
  UserX,
  UtensilsIcon,
  X,
} from "lucide-react";
import {
  FaApple,
  FaFacebook,
  FaGoogle,
  FaInstagram,
  FaTelegram,
  FaWhatsapp,
} from "react-icons/fa";

export type Icon = LucideIcon;

export const Icons = {
  alertCircle: AlertCircle,
  arrowLeft: ArrowLeft,
  bell: Bell,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  check: Check,
  circle: Circle,
  x: X,
  plus: Plus,
  minus: Minus,
  search: Search,
  spinner: Loader2,
  moreHorizontal: MoreHorizontal,
  panelLeft: PanelLeft,
  globe: Globe,
  gripVertical: GripVertical,
  layoutDashboard: LayoutDashboard,
  settings: Settings,
  slidersHorizontal: SlidersHorizontal,
  users: Users,
  moon: Moon,
  sun: Sun,
  circleCheck: CheckCircle2,
  info: Info,
  octagonX: OctagonX,
  triangleAlert: TriangleAlert,
  user: User2Icon,
  payments: LandmarkIcon,
  storefront: StoreIcon,
  orders: PackageIcon,
  products: ShoppingCart,
  home: HouseIcon,
  star: Star,
  google: FaGoogle,
  apple: FaApple,
  facebook: FaFacebook,
  telegram: FaTelegram,
  instagram: FaInstagram,
  logo: CompassIcon,
  key: Key,
  copy: Copy,
  shirt: ShirtIcon,
  laptop: LaptopIcon,
  utensils: UtensilsIcon,
  beauty: SparklesIcon,
  sports: TrophyIcon,
  books: BookIcon,
  toys: Gamepad2Icon,
  other: LayoutGridIcon,
  upload: Upload,
  package: PackageIcon,
  camera: CameraIcon,
  trash: Trash2Icon,
  truck: Truck,
  edit: PencilIcon,
  eye: Eye,
  eyeOff: EyeOff,
  upRight: ArrowUpRight,
  downRight: ArrowDownRight,
  lock: LockIcon,
  shoppingCart: ShoppingCartIcon,
  whatsapp: FaWhatsapp,
  play: CirclePlay,
  clock: Clock,
  fileText: FileText,
  mapPin: MapPin,
  megaphone: Megaphone,
  messageSquareX: MessageSquareX,
  userX: UserX,
  packageCheck: PackageCheck,
  phone: Phone,
  refreshCw: RefreshCw,
  share2: Share2,
  shieldCheck: ShieldCheck,
} as const;
